### getAllProducts (OK)
GET http://localhost:3306/products

### getShoppingList (OK)
GET http://localhost:3306/shp-list/79782e6a-4980-4cc0-b068-7bc320ca5483

### getUser (OK)
GET http://localhost:3306/profile/79782e6a-4980-4cc0-b068-7bc320ca5483

### createLogin (OK)
POST http://localhost:3306/login
Content-Type: application/json

{
    "email": "gi@gi.com",
    "password": "pwd"
}

### createShoppingItem (OK)
POST http://localhost:3306/shp-list
Content-Type: application/json

{
    "user_id": "79782e6a-4980-4cc0-b068-7bc320ca5483",
    "product": 
        { 
            "id": "20",
            "desired_qty": 40
        }
    
}

### createUser (OK)
POST http://localhost:3306/register
Content-Type: application/json

{
    "name": "GicaA",
    "zipcode": "80620100",
    "number": 100,
    "complement": "AP42",
    "day": 9,
    "email": "giovanna@gi.com",
    "password": "pwd123"
}

### deleteShoppingList (OK)
DELETE http://localhost:3306/shp-list/79782e6a-4980-4cc0-b068-7bc320ca5483


### deleteListItem (OK)
DELETE http://localhost:3306/shp-list/edit/:id


### alterShoppingList (OK)
PUT http://localhost:3306/shp-list/edit
Content-Type: application/json

{
    "user_id": "79782e6a-4980-4cc0-b068-7bc320ca5483",
    "new_item": 
        { 
            "id": 20,
            "desired_qty": 25
        }
    
} 